<?php

$files = [
    __DIR__ . '/../index.html',
    __DIR__ . '/../about.html',
    __DIR__ . '/../contact.html',
    __DIR__ . '/../login.html',
    __DIR__ . '/../signup.html',
    __DIR__ . '/../profile.html',
    __DIR__ . '/../admin_login.html',
    __DIR__ . '/../admin_dashboard.html',
    __DIR__ . '/../test_history.html',
    __DIR__ . '/../exercises_english.html',
    __DIR__ . '/../english/test.html',
    __DIR__ . '/login.js',
    __DIR__ . '/registration.js',
    __DIR__ . '/../main.js',
];

$replacements = [
    '<html lang="en">' => '<html lang="lv">',
    '<html lang="ru">' => '<html lang="lv">',
    '<meta http-equiv="Content-Language" content="en">' => '<meta http-equiv="Content-Language" content="lv">',
    'Language Learning Platform' => 'Valodu apguves platforma',
    'About Us' => 'Par mums',
    'Contacts' => 'Kontakti',
    'Contact' => 'Kontakti',
    'Login' => 'Pieteikties',
    'Sign up' => 'Reģistrēties',
    'Sign Up' => 'Reģistrēties',
    'Register' => 'Reģistrēties',
    'Create Account' => 'Izveidot kontu',
    'Join our language learning community' => 'Pievienojies mūsu valodu apguves kopienai',
    'Username or Email' => 'Lietotājvārds vai e-pasts',
    'Username' => 'Lietotājvārds',
    'Email Address' => 'E-pasta adrese',
    'Email' => 'E-pasts',
    'Password' => 'Parole',
    'Confirm Password' => 'Apstiprini paroli',
    'First Name' => 'Vārds',
    'Last Name' => 'Uzvārds',
    'Country' => 'Valsts',
    'Phone Number' => 'Tālruņa numurs',
    'Date of Birth' => 'Dzimšanas datums',
    'Select your date of birth' => 'Izvēlies savu dzimšanas datumu',
    'Gender' => 'Dzimums',
    'Select gender' => 'Izvēlies dzimumu',
    'Male' => 'Vīrietis',
    'Female' => 'Sieviete',
    'Already have an account?' => 'Vai tev jau ir konts?',
    'Sign In' => 'Pieteikties',
    "Don't have an account?" => 'Vēl nav konta?',
    'Welcome Back' => 'Prieks tevi redzēt atkal',
    'Admin Login' => 'Administratora pieslēgšanās',
    'Admin Email' => 'Administratora e-pasts',
    'Sign In as Admin' => 'Pieslēgties kā administrators',
    'Get in Touch' => 'Sazinies ar mums',
    "We'd love to hear from you. Send us a message and we'll respond as soon as possible." => 'Mēs labprāt uzklausīsim tevi. Nosūti mums ziņu, un mēs atbildēsim pēc iespējas ātrāk.',
    'Send Message' => 'Nosūtīt ziņu',
    'Full Name' => 'Pilns vārds',
    'Enter your full name' => 'Ievadi savu pilno vārdu',
    'Subject' => 'Temats',
    'What is this about?' => 'Par ko ir šī ziņa?',
    'Message' => 'Ziņa',
    'Tell us more details...' => 'Pastāsti vairāk...',
    'Contact Information' => 'Kontaktinformācija',
    'Email Us' => 'Raksti mums',
    'Call Us' => 'Zvani mums',
    'Visit Us' => 'Apmeklē mūs',
    'Business Hours' => 'Darba laiks',
    'Monday - Friday: 9:00 AM - 6:00 PM' => 'Pirmdiena - piektdiena: 9:00 - 18:00',
    'Saturday: 10:00 AM - 4:00 PM' => 'Sestdiena: 10:00 - 16:00',
    'Sunday: Closed' => 'Svētdiena: slēgts',
    'Follow Us' => 'Seko mums',
    'Download Our Apps' => 'Lejupielādē mūsu lietotnes',
    'Download on the' => 'Lejupielādē no',
    'Get it on' => 'Pieejams',
    'Stay Updated' => 'Saņem jaunākās ziņas',
    'Get the latest news and updates about new courses' => 'Saņem jaunākās ziņas par jaunajiem kursiem',
    'Enter your email address' => 'Ievadi savu e-pasta adresi',
    'Subscribe' => 'Abonēt',
    'Resources' => 'Resursi',
    'Grammar' => 'Gramatika',
    'Vocabulary' => 'Vārdu krājums',
    'Pronunciation' => 'Izruna',
    'Exercises' => 'Vingrinājumi',
    'Tests' => 'Testi',
    'Certificates' => 'Sertifikāti',
    'Support' => 'Atbalsts',
    'Help Center' => 'Palīdzības centrs',
    'Contact Us' => 'Sazinies ar mums',
    'FAQ' => 'Biežāk uzdotie jautājumi',
    'Feedback' => 'Atsauksmes',
    'Technical Support' => 'Tehniskais atbalsts',
    'Company' => 'Uzņēmums',
    'Our Team' => 'Mūsu komanda',
    'Careers' => 'Karjera',
    'Press' => 'Prese',
    'Partners' => 'Partneri',
    'Blog' => 'Blogs',
    'All rights reserved.' => 'Visas tiesības aizsargātas.',
    'Platform Version' => 'Platformas versija',
    'Last Updated' => 'Pēdējoreiz atjaunināts',
    'Privacy Policy' => 'Privātuma politika',
    'Terms of Service' => 'Lietošanas noteikumi',
    'Cookie Policy' => 'Sīkdatņu politika',
    'Security' => 'Drošība',
    'Accessibility' => 'Pieejamība',
    'Level Up Your Language Skills' => 'Attīsti savas valodu prasmes',
    'Join our immersive platform to boost your language abilities through interactive lessons and community support.' => 'Pievienojies mūsu platformai, lai attīstītu valodu prasmes ar interaktīvām nodarbībām un kopienas atbalstu.',
    'Get Started Now' => 'Sāc tagad',
    'Our Features' => 'Mūsu priekšrocības',
    'Expert Tutors' => 'Pieredzējuši pasniedzēji',
    'Work with language professionals to guide you to fluency.' => 'Mācies kopā ar valodu profesionāļiem ceļā uz brīvu saziņu.',
    'Interactive Lessons' => 'Interaktīvas nodarbības',
    'Engage with lessons tailored to your needs and learning style.' => 'Iesaisties nodarbībās, kas pielāgotas tavām vajadzībām un mācību stilam.',
    'Community Support' => 'Kopienas atbalsts',
    'Collaborate with fellow learners and receive helpful feedback.' => 'Sadarbojies ar citiem apguvējiem un saņem noderīgu atgriezenisko saiti.',
    'Choose Your Language' => 'Izvēlies savu valodu',
    'Start Learning' => 'Sākt mācīties',
    'My Profile' => 'Mans profils',
    'Welcome, ' => 'Sveika, ',
    'View Test History' => 'Skatīt testu vēsturi',
    'Logout' => 'Izrakstīties',
    'Security Settings' => 'Drošības iestatījumi',
    'For security reasons, password changes are currently disabled.' => 'Drošības apsvērumu dēļ paroles maiņa pašlaik nav pieejama.',
    'If you need to change your password, please contact support.' => 'Ja tev nepieciešams nomainīt paroli, sazinies ar atbalstu.',
    'Account Settings' => 'Konta iestatījumi',
    'Notifications' => 'Paziņojumi',
    'Email Notifications' => 'E-pasta paziņojumi',
    'Progress Updates' => 'Progresa atjauninājumi',
    'Marketing Emails' => 'Mārketinga e-pasti',
    'Privacy' => 'Privātums',
    'Make profile public' => 'Padarīt profilu publisku',
    'Share progress with friends' => 'Kopīgot progresu ar draugiem',
    'Save Settings' => 'Saglabāt iestatījumus',
    'Loading...' => 'Ielādējas...',
    'Administrator Panel' => 'Administratora panelis',
    'Admin' => 'Administrators',
    'Welcome Back!' => 'Prieks redzēt atkal!',
    'Manage your language learning platform from one central hub' => 'Pārvaldi savu valodu apguves platformu no vienas centrālās vietas.',
    'Total Users' => 'Kopējais lietotāju skaits',
    'Active Courses' => 'Aktīvie kursi',
    'Total Lessons' => 'Kopējais nodarbību skaits',
    'New Registrations' => 'Jaunas reģistrācijas',
    'Quick Actions' => 'Ātrās darbības',
    'Perform common administrative tasks quickly' => 'Ātri veic biežākos administratīvos uzdevumus.',
    'Add New User' => 'Pievienot jaunu lietotāju',
    'Create Course' => 'Izveidot kursu',
    'Add Lesson' => 'Pievienot nodarbību',
    'Generate Report' => 'Ģenerēt atskaiti',
    'Recent Activity' => 'Jaunākās aktivitātes',
    'User Management' => 'Lietotāju pārvaldība',
    'Manage platform users, their roles and access' => 'Pārvaldi platformas lietotājus, viņu lomas un piekļuves tiesības.',
    'Created At' => 'Izveidots',
    'Last Login' => 'Pēdējā pieslēgšanās',
    'Status' => 'Statuss',
    'Actions' => 'Darbības',
    'Course Management' => 'Kursu pārvaldība',
    'Manage your language learning courses and content' => 'Pārvaldi valodu apguves kursus un saturu.',
    'Course Statistics' => 'Kursu statistika',
    'Total Courses' => 'Kopējais kursu skaits',
    'Active Students' => 'Aktīvie studenti',
    'Completed Lessons' => 'Pabeigtās nodarbības',
    'Average Progress' => 'Vidējais progress',
    'Available Courses' => 'Pieejamie kursi',
    'Search courses...' => 'Meklēt kursus...',
    'All Languages' => 'Visas valodas',
    'Course Name' => 'Kursa nosaukums',
    'Language' => 'Valoda',
    'Level' => 'Līmenis',
    'Students' => 'Studenti',
    'Progress' => 'Progress',
    'Analytics' => 'Analītika',
    'View platform statistics and analytics' => 'Skati platformas statistiku un analītiku.',
    'Timezone' => 'Laika josla',
    'Add User' => 'Pievienot lietotāju',
    'Cancel' => 'Atcelt',
    'Confirm' => 'Apstiprināt',
    'System' => 'Sistēma',
    'Course creation functionality will be implemented later' => 'Kursa izveides funkcija tiks pievienota vēlāk.',
    'Lesson addition functionality will be implemented later' => 'Nodarbību pievienošanas funkcija tiks pievienota vēlāk.',
    'Report generation functionality will be implemented later' => 'Atskaites ģenerēšanas funkcija tiks pievienota vēlāk.',
    'Delete User' => 'Dzēst lietotāju',
    'Are you sure you want to delete this user? This action cannot be undone.' => 'Vai tiešām vēlies dzēst šo lietotāju? Šo darbību nevar atsaukt.',
    'Test History' => 'Testu vēsture',
    'Home' => 'Sākums',
    'Back to Profile' => 'Atpakaļ uz profilu',
    'Average Score' => 'Vidējais rezultāts',
    'Total Time' => 'Kopējais laiks',
    'Topics Covered' => 'Apskatītās tēmas',
    'Question' => 'Jautājums',
    'Your Answer' => 'Tava atbilde',
    'Correct Answer' => 'Pareizā atbilde',
    'No test results found' => 'Testu rezultāti nav atrasti',
];

foreach ($files as $file) {
    $content = file_get_contents($file);
    if ($content === false) {
        continue;
    }

    $updated = str_replace(array_keys($replacements), array_values($replacements), $content);
    file_put_contents($file, $updated);
}

echo "Localization applied.\n";
